spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ISAIFI/olx-config
          default-label: main
          username: ISAIFI
          password: aa@320931
          clone-on-start: true
          
server:
  port: 8888